# serverless.yml

service: koa-app2

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2

functions:
  koa2:
    handler: code/server/app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'